language: node_js
sudo: false

env:
  - SENECA_VER=senecajs/seneca
  - SENECA_VER=seneca@plugin
  - SENECA_VER=seneca@3

node_js:
  - '13'
  - '12'
  - '10'
  - '8'

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
